import tseslint from "@typescript-eslint/eslint-plugin";
import tsparser from "@typescript-eslint/parser";
import solid from "eslint-plugin-solid";
import js from "@eslint/js";

export default [
  {
    ignores: ["dist", "node_modules", "coverage", "playwright-report", "test-results"],
  },
  js.configs.recommended,
  {
    files: ["**/*.{ts,tsx}"],
    languageOptions: {
      parser: tsparser,
      parserOptions: { ecmaVersion: 2022, sourceType: "module" },
      globals: {
        window: "readonly",
        document: "readonly",
        console: "readonly",
        process: "readonly",
        HTMLElement: "readonly",
        HTMLDivElement: "readonly",
        HTMLInputElement: "readonly",
        HTMLSelectElement: "readonly",
        HTMLTextAreaElement: "readonly",
        HTMLButtonElement: "readonly",
        Node: "readonly",
        WebSocket: "readonly",
        URL: "readonly",
        Request: "readonly",
        RequestInit: "readonly",
        Headers: "readonly",
        Response: "readonly",
        fetch: "readonly",
        localStorage: "readonly",
        SubmitEvent: "readonly",
        MouseEvent: "readonly",
        KeyboardEvent: "readonly",
        RequestInfo: "readonly",
        getComputedStyle: "readonly",
        setTimeout: "readonly",
        clearTimeout: "readonly",
        setInterval: "readonly",
        clearInterval: "readonly",
        performance: "readonly",
        URLSearchParams: "readonly",
        PointerEvent: "readonly",
        self: "readonly",
        queueMicrotask: "readonly",
        navigator: "readonly",
        FormData: "readonly",
        File: "readonly",
        Blob: "readonly",
        DataTransfer: "readonly",
        ClipboardEvent: "readonly",
        DragEvent: "readonly",
        HTMLImageElement: "readonly",
        Event: "readonly",
        __dirname: "readonly",
        __filename: "readonly",
      },
    },
    plugins: {
      "@typescript-eslint": tseslint,
      solid,
    },
    rules: {
      ...tseslint.configs.recommended.rules,
      ...solid.configs.typescript.rules,
    },
  },
];
