
# cargo-audit configuration

[advisories]
ignore = [
    "RUSTSEC-2017-0008",
    "RUSTSEC-2023-0071",
    "RUSTSEC-2025-0021",
    "RUSTSEC-2025-0140",
    "RUSTSEC-2026-0185",
    "RUSTSEC-2026-0186",
    "RUSTSEC-2026-0204",
    "RUSTSEC-2026-0190",
    "RUSTSEC-2026-0221"
]

[yanked]
enabled = false
